<a href="https://colab.research.google.com/github/aaddobea/PyTorch-Fundamentals/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **PyTorch Fundamentals: Dive into Hands-on Deep Learning**
==============================================================

**Get Started with PyTorch: Tensors and Operations**
-----------------------------------------------------------

> This notebook is designed to introduce you to the fundamentals of PyTorch, a popular deep learning framework. Through clear examples and detailed explanations, you'll learn the basics of:

* Tensor initialization
* Tensor operations
* Indexing and slicing
* Reshaping tensors

Follow along to gain hands-on experience with PyTorch and set yourself up for success in your deep learning journey.


# Table of Contents

### Tensors Fundamentals

* [What are Tensors?](#What-are-Tensors?)
* [Tensor Initialization](#Tensor-Initialization)
* [Common Tensor Initialization Methods](#Common-Tensor-Initialization-Methods)

### Tensor Manipulation

* [Tensor Type Conversion](#Tensor-Type-Conversion)
* [Converting Between NumPy Arrays and Tensors](#Converting-Between-NumPy-Arrays-and-Tensors)

### Tensor Operations

* [Tensor Mathematics and Comparison Operations](#Tensor-Mathematics-and-Comparison-Operations)
* [Matrix Multiplication and Batch Operations](#Matrix-Multiplication-and-Batch-Operations)
* [Broadcasting and Other Useful Operations](#Broadcasting-and-Other-Useful-Operations)

### Tensor Transformation

* [Tensor Indexing](#Tensor-Indexing)
* [Tensor Reshaping](#Tensor-Reshaping)

In [3]:
!pip install numpy

In [4]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 125.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 96.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 104.4 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitl

In [3]:
import torch
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Print versions
print("torch version:", torch.__version__)
print("numpy version:", np.__version__)

torch version: 2.6.0+cu124
numpy version: 2.0.2


## Initialising a tensor

The following code demonstrates how to create a 2×3 PyTorch tensor with a float32 data type, place it on either CPU or GPU (depending on availability), and enable gradient tracking for automatic differentiation.

In [4]:
# Check for CUDA availability and set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize a 2x3 tensor with requires_grad enabled
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print("Data type:", my_tensor.dtype)
print("Device:", my_tensor.device)
print("Shape:", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
Data type: torch.float32
Device: cuda:0
Shape: torch.Size([2, 3])
Requires Gradient: True


##Common Tensor Methods


1. **Empty Tensor:** How to create an unintialised 3x3 tensor filled with zeros.
2. **Zero Tensor:** Create a Tensor filled with only zeros.
3. **Random Tensor:** How to create a tensor filled with random values varrying between 0 and 1.
4. **Ones Tensor:** How to create a Tensor filled with only ones.
5. **Identity Matrix:** This type of tensor generates a 4x4 identity matrix  with diagonal consisting of ones.
6. **Arange Tensor:** Creates a 1-dimensional tensor with values ranging from 0 to 4 with an increment of 1.
7. **Linespace Tensor:** This type of tensor generate a 5x5 evenly spaced tensor with values ranging between 0.1 and 1.
8. **Normal Distributed Tensor:**  This tensor fills a tensor with values from a noraml (Gaussian) distribution with mean 0 and a standard deviation of 1.
9. **Uniform Distributed Tensor:** It's a tensor filled with values from a uniform distribution between O and 1.
10. **Diagonal Tensor:** This type of tensor creates a 4x4 diagonal tensor with ones along the diagonal and zeros.  





In [6]:
#Creating a 6x6 empty tensor
x = torch.empty(6,6)
x

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [9]:
# Create a tensor filled with zeros
x = torch.zeros(6, 6)
x

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [8]:
#Creates a tensor with random values
x=torch.rand(6,6)
x

tensor([[0.6298, 0.5027, 0.9704, 0.7509, 0.9250, 0.5062],
        [0.8393, 0.0021, 0.0624, 0.4847, 0.8281, 0.0524],
        [0.2878, 0.2016, 0.8716, 0.2949, 0.9506, 0.9160],
        [0.6528, 0.5802, 0.1824, 0.2500, 0.6889, 0.9897],
        [0.4096, 0.1905, 0.3617, 0.9430, 0.6647, 0.8725],
        [0.1612, 0.9256, 0.5209, 0.6850, 0.6689, 0.7762]])

In [10]:
#Creates a tensor filled with only ones
x=torch.ones(6,6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
#Create an identity Matrix
x=torch.eye(6,6)
x

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [12]:
#Create a tensor using arange
x=torch.arange(8,dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [18]:
#Create a linspace tensor
x = torch.linspace(0.5, 5, steps=10)
x

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000,
        5.0000])

In [20]:
# A normal distribution tensor
x=torch.normal(mean=4,std=2,size=(6,6))
x

tensor([[ 1.4764,  0.9199,  5.9423,  2.6484, -0.0114,  5.2768],
        [ 3.0782,  4.2619,  2.5181,  1.9943,  2.7766,  0.1989],
        [ 3.0370,  5.9030,  6.1878,  3.3009, -0.6036,  2.6345],
        [ 3.4277,  5.4019,  0.4103,  2.8914,  6.7001,  0.5340],
        [ 8.3322,  1.5504,  6.7575,  3.2842,  2.2773,  0.5482],
        [ 2.4567,  4.2741,  3.8844,  6.8725,  3.4687,  5.4158]])

In [22]:
# still on a normal distribution tensor
x=torch.empty(1,5).normal_(mean=4,std=2)
x


tensor([[ 2.0910, -1.3339,  5.0517,  1.8393, -0.1877]])

In [23]:
# A uniform distribution tensor
x = torch.empty(1, 5).uniform_(0, 1)
x

tensor([[0.0914, 0.5603, 0.0864, 0.0635, 0.7046]])

In [7]:
# Diagonal tensor
x=torch.diag(torch.ones(6))
x

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

## Tensor Type  Conversion

Here, we create a tensor with values [0,1,2,3] and also demonstrates type conversion to boolean, int16,int64,float16,float32 and float64.

In [9]:
tensor = torch.arange (6)
print(tensor)
print(tensor.dtype)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())


tensor([0, 1, 2, 3, 4, 5])
torch.int64
tensor([False,  True,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4, 5], dtype=torch.int16)
tensor([0, 1, 2, 3, 4, 5])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4., 5.])
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


## Converting Between Numpy Arrays and Tensors

PyTorch provides a convenient interface for converting between NumPy arrays and tensors, enabling effortless integration with existing computational workflows.



In [10]:
# Create a Numpy array of Zeros.
#This code snippet uses the NumPy library to create a NumPy array filled with zeros. However, the code to create the array is missing from the cell.

np_array = np.zeros((6,6))
np_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
# Convert from Numpy array to PyTorch tensor
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [13]:
# Convert tensor back to Numpy array
numpy_back = tensor.numpy ()
numpy_back

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Tensor Mathematics and Operation Comparison

This section utilizes math operations with PyTorch Tensors.

1. **Addition & Subtraction-** Adds (+) and Subtracts (-) two tensor elements.
2. **Division-** Uses the division (-)operator for precise results.
3. **Exponentiation-** Utilises power operation (pow **).
4. **Boolean-** Utilises boolean operators like (<,>,=) to return boolean results.
5. **Dot Product-** Computes the sum of the element-wise product of two tensors, returning a scalar value.
6. **Inplace Operations-** Modifies a tensor directly without creating a new one.



In [6]:
x = torch.tensor([1,3,5,7,9])
y = torch.tensor([2,4,6,8,10])

#Addition- Adds two tensors
z=torch.add(x,y)
z1=x+y
print(z)
print(z1)


tensor([ 3,  7, 11, 15, 19])
tensor([ 3,  7, 11, 15, 19])


In [17]:
#Subtraction- Performs a subtraction operation on two tensors
z2=torch.subtract(x,y)
z3= x- y
print(z2)
print(z3)

tensor([-1, -1, -1, -1, -1])
tensor([-1, -1, -1, -1, -1])


In [19]:
#Division- Perform a division of two tensors
z4=torch.divide(x,y)
z5= x// y
print(z4)
print(z5)

tensor([0.5000, 0.7500, 0.8333, 0.8750, 0.9000])
tensor([0, 0, 0, 0, 0])


In [20]:
# Exponentiation#
z6=torch.pow(x,y)
z7=x**y
print(z6)
print(z7)

tensor([         1,         81,      15625,    5764801, 3486784401])
tensor([         1,         81,      15625,    5764801, 3486784401])


In [7]:
# Boolean Operations
z8 =x > 0
x

z9 = x<0
x

tensor([1, 3, 5, 7, 9])

In [8]:
#Dot Product
zDot =torch.dot(x,y)
zDot

tensor(190)

In [11]:
# Inplace operations
t = torch.ones(5)
print("Before inplace addition:", t)
t.add_(x)
print("After inplace addition:", t)
t += x  # Another inplace addition (note: t = t + x creates a new tensor)
print("After second inplace addition:", t)

Before inplace addition: tensor([1., 1., 1., 1., 1.])
After inplace addition: tensor([ 2.,  4.,  6.,  8., 10.])
After second inplace addition: tensor([ 3.,  7., 11., 15., 19.])


## Matrix Multiplication and Batch Operations

Matrix operations are at the heart of deep learning. Let's find out different ways to perform multiplication.

1. **Matrix Multiplication:** Uses `@` or `torch.mm()` to perform standard matrix multiplication.  
2. **Matrix Exponentiation:** Raises a square matrix to a power using `matrix_power(n)`.
3. **Element-wise Multiplication:** Uses `torch.mul()` or `*` for element-wise multiplication.  






In [7]:
## Matrix Multiplication and Batch Operations

### Example Code
# Define two matrices
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6, 9], [7, 8, 1]])

# Matrix Multiplication
C = A @ B
print("Matrix Multiplication: \n", C)

C = torch.mm(A, B)
print("Matrix Multiplication: \n", C)


# Matrix Exponentiation
D = torch.linalg.matrix_power(A, 2)
print("Matrix Exponentiation: \n", D)


Matrix Multiplication: 
 tensor([[19, 22, 11],
        [43, 50, 31]])
Matrix Multiplication: 
 tensor([[19, 22, 11],
        [43, 50, 31]])
Matrix Exponentiation: 
 tensor([[ 7, 10],
        [15, 22]])


In [13]:
# Element-wise Multiplication
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
E = torch.mul(A, B)
print("Element-wise Multiplication: \n", E)
# #Alternative option
E = A * B
print("Element-wise Multiplication: \n", E)

Element-wise Multiplication: 
 tensor([[ 5, 12],
        [21, 32]])
Element-wise Multiplication: 
 tensor([[ 5, 12],
        [21, 32]])


## **Batch Matrix Multiplication**:
1. Batch Matrix Multiplication: Uses torch.bmm() to perform batch matrix multiplication.
2. Batch Element-wise Multiplication: Uses torch.mul() or * for batch element-wise multiplication.



In [14]:
# Define two batches of matrices
A_batch = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
B_batch = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
# Batch Matrix Multiplication
C_batch = torch.bmm(A_batch, B_batch)
print("Batch Matrix Multiplication: \n", C_batch)
# Batch Element-wise Multiplication
E_batch = torch.mul(A_batch, B_batch)
print("Batch Element-wise Multiplication: \n", E_batch)

Batch Matrix Multiplication: 
 tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])
Batch Element-wise Multiplication: 
 tensor([[[  9,  20],
         [ 33,  48]],

        [[ 65,  84],
         [105, 128]]])


In [21]:
#Another example of batch matrix application
batch = 98
x, y, z = 17, 32, 55
tensor1 = torch.rand(batch, x, y)
tensor2 = torch.rand(batch, y, z)
out = torch.bmm(tensor1, tensor2) # so=hows the shape of the tensor
print("Batch Matrix (first batch):\n", out[0])
print("The shape of the batch multiplication results in:\n", out.shape) # Prints out the shape of tensor

Batch Matrix (first batch):
 tensor([[ 7.9254,  8.2898,  8.8852,  8.5008,  9.5825,  7.8063,  9.5218,  7.7836,
          6.6981,  8.4224,  7.6196,  9.4367,  9.4317,  9.8519,  9.6635,  9.2708,
          8.1381, 10.0274,  8.5507,  8.9452,  8.1529,  6.5712,  8.8871,  8.3546,
          7.2615,  9.1037,  8.7985,  8.2919, 10.7117,  6.9423,  9.5739, 10.0594,
          7.5436,  8.6067,  8.2466,  8.5262,  8.1657,  7.6389,  8.7156,  7.5846,
          6.5544,  8.7840,  8.4811,  8.1190,  7.0277,  9.9651,  8.3882,  6.8276,
          8.8472, 10.3327, 10.2817,  9.5997,  7.1074,  8.8534,  8.9884],
        [ 9.0653,  9.1128,  9.0702,  9.6404, 10.4345,  8.7031, 11.4447,  8.8373,
          8.2881,  9.7086,  7.5609,  9.5735,  9.2124,  9.4276,  9.9335,  9.1532,
          7.7927,  9.3934,  9.6356,  8.9065,  9.3138,  8.2064,  9.5772,  8.1508,
          7.1188,  8.6680,  9.7052,  8.6118, 11.6432,  8.2899,  9.3980, 10.5476,
          7.3169,  7.9121,  9.0234,  9.0174,  8.1514,  8.3660,  7.8828,  8.3493,
       

##**Broadcasting and Other Useful Operations**

> Broadcasting allows arithmetic operations on tensors of different shapes. This section also demonstrates additional useful functions.

- **Broadcasting:** Automatically expands smaller tensors to match larger ones in operations.  
- **Summation:** `torch.sum(x, dim=0)` computes sum along a specific dimension.  
- **Min/Max Values:** `torch.max()` and `torch.min()` return the highest and lowest values along a dimension.  
- **Absolute Values:** `torch.abs(x)` gets the element-wise absolute values.  
- **Argmax/Argmin:** `torch.argmax()` and `torch.argmin()` return the index of max/min values.  
- **Mean Calculation:** `torch.mean(x.float(), dim=0)` computes the mean (ensuring float dtype).  
- **Element-wise Comparison:** `torch.eq(x, y)` checks equality between two tensors.  
- **Sorting:** `torch.sort(y, dim=0)` sorts tensor elements and returns indices.  
- **Clamping:** `torch.clamp(x, min=0)` restricts values within a range.  
- **Boolean Operations:** `torch.any(x_bool)` checks if any value is `True`, `torch.all(x_bool)` checks if all are `True`.

In [32]:
# Define tensors with descriptive names

matrix = torch.rand(5, 5)
vector = torch.rand(5)

# Print tensors with clear labels
print("Matrix (5x5):\n", matrix)
print("Vector (5):\n", vector)

# Perform broadcasting operations
broadcasted_subtraction = matrix - vector
broadcasted_power = matrix ** vector

# Print results with descriptive labels
print("Matrix - Vector (broadcasted subtraction):\n", broadcasted_subtraction)
print("Matrix raised to the power of Vector (broadcasted power):\n", broadcasted_power)

# Summation of tensor elements along a dimension 0
sum_along_dim0 = torch.sum(matrix,dim=0)
print("Sum along dimension 0:\n", sum_along_dim0)

# Determining the Maximum and **Mininum** values of a tensor with 0-dimension
value_max, index_max = torch.max(matrix, dim = 0)
value_min, index_min = torch.min(matrix, dim =0)
print("Maximum Values (along dimension 0):\n", value_max)
print("Indices of Maximum Values (along dimension 0):\n", index_max)

print("Minimum Values (along dimension 0):\n", value_min)
print("Indices of Minimum Values (along dimension 0):\n", index_min)


Matrix (5x5):
 tensor([[0.9981, 0.7560, 0.8607, 0.5471, 0.6866],
        [0.3240, 0.9405, 0.0533, 0.6738, 0.7865],
        [0.5608, 0.4181, 0.3402, 0.2968, 0.4588],
        [0.0207, 0.1091, 0.0662, 0.2091, 0.6319],
        [0.6682, 0.1788, 0.1994, 0.0287, 0.4932]])
Vector (5):
 tensor([0.2968, 0.7401, 0.6726, 0.5835, 0.8406])
Matrix - Vector (broadcasted subtraction):
 tensor([[ 0.7013,  0.0159,  0.1880, -0.0364, -0.1540],
        [ 0.0272,  0.2004, -0.6193,  0.0903, -0.0541],
        [ 0.2640, -0.3220, -0.3325, -0.2867, -0.3818],
        [-0.2761, -0.6310, -0.6064, -0.3744, -0.2087],
        [ 0.3714, -0.5614, -0.4733, -0.5548, -0.3474]])
Matrix raised to the power of Vector (broadcasted power):
 tensor([[0.9994, 0.8130, 0.9040, 0.7033, 0.7290],
        [0.7157, 0.9556, 0.1392, 0.7942, 0.8172],
        [0.8423, 0.5244, 0.4842, 0.4922, 0.5195],
        [0.3163, 0.1941, 0.1611, 0.4013, 0.6798],
        [0.8872, 0.2797, 0.3380, 0.1259, 0.5520]])
Sum along dimension 0:
 tensor([2.5718, 2.

In [35]:
# Define tensors x and y
x = torch.tensor([1,5,6])  # Replace with actual values
y = torch.tensor([7,9,2])  # Replace with actual values
# Compute and print various tensor operations
print("Absolute Values:")
print(torch.abs(x))
print("\nArgmax (along dimension 0):")
print(torch.argmax(x, dim=0))
print("\nArgmin (along dimension 0):")
print(torch.argmin(x, dim=0))
print("\nMean (converted to float, along dimension 0):")
print(torch.mean(x.float(), dim=0))
print("\nElement-wise Equality (x == y):")
print(torch.eq(x, y))

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print("Sorted y and indices:", sorted_y, indices)

# Sorting
top_k_values, top_k_indices = torch.topk(x, k=3, dim=0)
print("Top-k values and indices:", top_k_values, top_k_indices)

# Clamp values to a minimum of 0
clamped_x = torch.clamp(x, min=0)
print(f"Clamped x: {clamped_x}")

Absolute Values:
tensor([1, 5, 6])

Argmax (along dimension 0):
tensor(2)

Argmin (along dimension 0):
tensor(0)

Mean (converted to float, along dimension 0):
tensor(4.)

Element-wise Equality (x == y):
tensor([False, False, False])
Sorted y and indices: tensor([2, 7, 9]) tensor([2, 0, 1])
Top-k values and indices: tensor([6, 5, 1]) tensor([2, 1, 0])
Clamped x: tensor([1, 5, 6])


In [30]:
# Define a boolean tensor
x_bool = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
# Perform boolean operations
any_true = torch.any(x_bool)
all_true = torch.all(x_bool)
# Print results
print(f"Any True: {any_true}")
print(f"All True: {all_true}")

Any True: True
All True: False


## **Tensor Indexing**

> Access and modify tensor elements using indexing, slicing, and advanced indexing techniques.

---


## Accessing Rows and Columns

*   Rows: Use x[row, :] to access a specific row.
*   Columns: Use x[:, col] to access a specific column.

## Slicing
Row Slicing: x[row, start:end] extracts a portion of a row.

## Modifying Elements
Direct Assignment: Assign values directly using x[row, col] = value.

# Advanced Indexing Techniques
- **Fancy Indexing:** Use a list of indices to select multiple elements at once.
- **Conditional Indexing**: Extract elements using conditions like (x < 2) | (x > 8).
- **Finding Even Numbers:** Use x.remainder(2) == 0 to filter even values.

#Conditional Selection with torch.where()
- **Conditional Choice:** Use torch.where() to choose values based on a condition.

In [20]:
# Creating a random tensor with shape (batch size and reatures)
batch_size = 50
features = 10
x = torch.rand(batch_size, features)

#Print the first row
print("This is the first row of the tensor:\n", x[0,:])

#Print the second row
print("This is the second row of the tensor:\n", x[1,:])


#Print the first column
print("This is the first row of the tensor:\n", x[:,0])

#Output the second column
print("This is the second column of the tensor:\n", x[:,1])

#Print the first 10 elements of the third row
print("This is the first 10 elements of the third row:\n", x[2,0:10])

#Modify specific element  (set first element to 100)
x[0,0]=100
print(x)

#Fancy indexing example
x =torch.arange(70)
indices =[8,9, 10]
print("fancy indexing result", x[indices])

#Advanced indexing : select elements based on a condition
x1 = torch.arange(70)
print("Elements where x1 < 70 or x1 > 90:",x1[(x1<70) | (x1 > 90)])
print("Even numbers in x1:", x1[x1.remainder(2)==0])

#Using torch  to select values based on a condition
print("Using torch.where:", torch.where(x1 > 7, x1 * 2, x1))

#selection option 2
x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([10, 20, 30, 40, 50])
condition = torch.tensor([True, False, True, False, True])
selected_values = torch.where(condition, x, y)
print(selected_values)

This is the first row of the tensor:
 tensor([0.6095, 0.8770, 0.3208, 0.3880, 0.6311, 0.8887, 0.6308, 0.9437, 0.1765,
        0.1308])
This is the second row of the tensor:
 tensor([0.9535, 0.4668, 0.2816, 0.6225, 0.0927, 0.1929, 0.8161, 0.2866, 0.6681,
        0.9034])
This is the first row of the tensor:
 tensor([0.6095, 0.9535, 0.0645, 0.4010, 0.3723, 0.1730, 0.9011, 0.5818, 0.0469,
        0.2166, 0.0636, 0.7635, 0.9885, 0.5974, 0.2896, 0.5804, 0.6550, 0.5179,
        0.3225, 0.0704, 0.6223, 0.0456, 0.8093, 0.3715, 0.9279, 0.7162, 0.4381,
        0.3982, 0.9193, 0.2314, 0.3837, 0.4606, 0.8543, 0.1102, 0.3958, 0.9994,
        0.9273, 0.7551, 0.4869, 0.8329, 0.6730, 0.7639, 0.5675, 0.5939, 0.9000,
        0.0152, 0.6001, 0.1936, 0.5897, 0.5686])
This is the second column of the tensor:
 tensor([0.8770, 0.4668, 0.7543, 0.6632, 0.1032, 0.3634, 0.9881, 0.2540, 0.8268,
        0.2256, 0.7529, 0.9086, 0.2848, 0.6988, 0.1978, 0.1997, 0.6152, 0.7463,
        0.3620, 0.0126, 0.4674, 0.2444, 

In [16]:
# Create a sample tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing rows and columns
print(x[0, :])  # prints: tensor([1, 2, 3])
print(x[:, 1])  # prints: tensor([2, 5, 8])

# Slicing
print(x[0, 1:3])  # prints: tensor([2, 3])

# Modifying elements
x[0, 0] = 10
print(x)  # prints: tensor([[10,  2,  3], [ 4,  5,  6], [ 7,  8,  9]])

# Fancy indexing
print(x[[0, 2], [0, 2]])  # prints: tensor([10,  9])

# Conditional indexing
print(x[(x < 2) | (x > 8)])  # prints: tensor([10,  9])

# Finding even numbers
print(x[x.remainder(2) == 0])  # prints: tensor([2, 4, 6, 8])

# Conditional selection with torch.where()
print(torch.where(x > 5, x, 0))  # prints: tensor([[0, 0, 0], [0, 0, 6], [7, 8, 9]])

tensor([1, 2, 3])
tensor([2, 5, 8])
tensor([2, 3])
tensor([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])
tensor([10,  9])
tensor([10,  9])
tensor([10,  2,  4,  6,  8])
tensor([[10,  0,  0],
        [ 0,  0,  6],
        [ 7,  8,  9]])


## **Tensor Reshaping**

> Learn how to reshape tensors, concatenate them, and change the order of dimensions.

- **Reshape with `view()` & `reshape()`:** Change tensor shape without altering data.  
- **Transpose & Flatten:** `.t()` transposes, `.contiguous().view(-1)` flattens.  
- **Concatenation:** `torch.cat([x1, x2], dim=0/1)` merges tensors along rows/columns.  
- **Flattening:** `.view(-1)` converts a tensor into a 1D array.  
- **Batch Reshaping:** `.view(batch, -1)` keeps batch size while reshaping.  
- **Permute Dimensions:** `.permute(0, 2, 1)` reorders dimensions efficiently.  
- **Unsqueeze for New Dimensions:** `.unsqueeze(dim)` adds singleton dimensions.





# Tensor Reshaping
===========================================================================

> Learn how to reshape tensors, concatenate them, and change the order of dimensions.



## Reshaping Tensors

#### Using `view()` and `reshape()`

>Change the shape of a tensor without altering its data.

*   `view()`: Returns a new tensor with the same data but with a different shape.
*   `reshape()`: Similar to `view()`, but returns a new tensor with a different shape.

#### Transpose and Flatten

*   `.t()`: Transposes a tensor.
*   `.contiguous().view(-1)`: Flattens a tensor into a 1D array.

### Concatenating Tensors

*   `torch.cat([x1, x2], dim=0/1)`: Concatenates two tensors along rows (dim=0) or columns (dim=1).

### Flattening Tensors

*   `view(-1)`: Converts a tensor into a 1D array.

### Batch Reshaping

*   `view(batch, -1)`: Reshapes a tensor while keeping the batch size intact.

### Permuting Dimensions

*   `permute(0, 2, 1)`: Reorders the dimensions of a tensor efficiently.

### Adding New Dimensions

*   `unsqueeze(dim)`: Adds a singleton dimension to a tensor.

### Example Use Cases

*   Reshaping a tensor to fit a specific model architecture.
*   Concatenating multiple tensors to create a larger dataset.
*   Flattening a tensor to prepare it for a fully connected layer.
*   Permuting dimensions to match the expected input format of a model.
*   Adding new dimensions to a tensor to enable broadcasting operations.


In [28]:
#Reshape a tensor using view and reshape
x = torch.arange (25)
x_5x5 = x.view(5,5)
print("Reshaped to 5x5 using view:\n",x_5x5)
x_5x5 = x.reshape(5,5)
print("Reshaped to 5x5 using reshape:\n",x_5x5)

#Transpose  and flatten  the tensor
y = x_5x5.t()
print("Transposed tensor:\n", y)
print("Flattened tensor:\n", y.contiguous().view(-1))

#Concatenation example
x = torch.rand(5,6)
y = torch.rand(5,6)
z = torch.cat([x,y], dim=0)
print("Concatenated tensor:\n", z)
print("Concatenated along dimension 0 (rows):", torch.cat([x, y], dim=0).shape)
print("Concatenated along dimension 1 (columns):", torch.cat([x, y], dim=1).shape)

Reshaped to 5x5 using view:
 tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
Reshaped to 5x5 using reshape:
 tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
Transposed tensor:
 tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])
Flattened tensor:
 tensor([ 0,  5, 10, 15, 20,  1,  6, 11, 16, 21,  2,  7, 12, 17, 22,  3,  8, 13,
        18, 23,  4,  9, 14, 19, 24])
Concatenated tensor:
 tensor([[0.6049, 0.8907, 0.6187, 0.3240, 0.7987, 0.6279],
        [0.9034, 0.1171, 0.5957, 0.3890, 0.8713, 0.3883],
        [0.7854, 0.9422, 0.6399, 0.1274, 0.0082, 0.5320],
        [0.5727, 0.5619, 0.3364, 0.0671, 0.4179, 0.9777],
        [0.1002, 0.9354, 0.3704, 0.6749, 0.9268, 0.0834],
        [0.9178, 0

In [39]:
#Reshape  with batch dimension
batch = 74
x = torch.rand(batch,2,5)
print("Reshaped to (batch,-1):",x.view(batch,-1).shape)

#Permute dimensions
z = x.permute(0,2,1)
print("Permuted tensor shape:",z.shape)

#Unsqueze examples (adding new dimensions)
x = torch.arange (20)
print ("original x:", x)
print("unsqueeze at dim 0:", x.unsqueeze(0))
print("unsqueeze at dim 1:", x.unsqueeze(1))

Reshaped to (batch,-1): torch.Size([74, 10])
Permuted tensor shape: torch.Size([74, 5, 2])
original x: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
unsqueeze at dim 0: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
unsqueeze at dim 1: tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])
